development:
  adapter: postgresql
  encoding: unicode
  database: addons_development
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: jgs4pg

test:
  adapter: postgresql
  encoding: unicode
  database: addons_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: jgs4pg

  staging:
    adapter: postgresql
    encoding: unicode
    database: addons_staging
    pool: 5
    username: postgres
    password:

production:
  adapter: postgresql
  encoding: unicode
  database: addons_production
  host: localhost
  port: 5432
  username: postgres
