development:
  adapter: postgresql
  encoding: unicode
  database: addons_development
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: jgs4pg

test:
  adapter: postgresql
  encoding: unicode
  database: addons_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: jgs4pg

production:
  adapter: postgresql
  encoding: unicode
  database: addons_production
  host: localhost
  port: 5432
  username: postgres
